apiVersion: v1
kind: pod
metadata:
  name: pod-node
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
               - key: env
                 operator: In
                 values:
                   - prod
    podAffinity:
      requiredDuringSchedulingIngoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - Blue
          topologyKey: kubernetes.io/zone
    podAntiAffinity:
      requiredDuringSchedulingIngoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: 
                operator: In
                values:
                  - Red
          topologyKey: kubernetes.io/
  containers:
     - name: mynginx-container
       image: nginx
       ports:
        - containerPort: 80
